env:
  es6: true
  node: true

extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended']

parserOptions:
  ecmaVersion: latest
  sourceType: module

parser: '@typescript-eslint/parser'

plugins: ['@typescript-eslint']

rules:
  # off   OR 0
  # warn  OR 1
  # error OR 2
  no-console: error # disable console
  no-var: error ## disable var
  quotes: [error, single, { avoidEscape: true }] ## Use single quotes
  indent: [error, 2, { SwitchCase: 1 }] ## Indent two spaces
  comma-dangle: [error, never] ## Prohibit end commas
  semi: [error, never] ## Prohibit end semicolons
  arrow-parens: [error, always] ## Arguments to arrow functions must be enclosed in parentheses
  array-bracket-spacing: [error, never] ## Prohibit spaces inside the array brackets
  brace-style: error ## Force one true brace style
  camelcase: warn ## Force property name to hump style
  computed-property-spacing: [error, never] ## Prohibit the use of spaces within calculated attributes
  curly: [error, multi-line] ## https://cn.eslint.org/docs/rules/curly#multi
  eol-last: [error, always] ## Forced use of line feeds (LF)
  eqeqeq: [error, smart] ## https://cn.eslint.org/docs/rules/eqeqeq#smart
  max-depth: [error, 3] ## Maximum nesting depth for mandatory block statements
  max-len: [warn, 120] ## Line feed after 120 characters
  max-statements: [warn, 20] ## Limit the maximum number of statements in a function block
  new-cap: [warn, { capIsNew: false }] ## Requires constructors to be initialized with capital letters
  no-extend-native: error ## Disable extension of native types
  no-mixed-spaces-and-tabs: error ## Disable mixed indentation of spaces and tabs
  no-trailing-spaces: error ## Disable end-of-line spaces
  no-unused-vars: 1 ## Prohibit the appearance of unused variables
  no-use-before-define: [error, nofunc] ## Prohibit the use of variables before they are defined
  object-curly-spacing: [error, always] ## No spaces in brackets allowed
  keyword-spacing: [error, { before: true, after: true }] ## Force the use of consistent spaces before and after keywords
  space-unary-ops: error ## Prohibit spaces before or after unary operators
