packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  deps:
    body-data: ^2.0.1
    puppeteer: ^24.8.2
    puppeteer-core: ^24.8.2
  devDeps:
    nodemon: ^3.1.10
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2

onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - simple-git-hooks
  - unrs-resolver
